use DataWarehouseAnalytics;

-- Explore All Objects in the Database(Exploreing the structure of our database by writing a query)

select * from INFORMATION_SCHEMA.TABLES

-- Explore All Columns in the Database

select * from INFORMATION_SCHEMA.COLUMNS

where TABLE_NAME = 'dim_customers';

-- Dimensions Exploration

select * from gold.dim_customers;

select * from gold.dim_products;

select * from gold.fact_sales;

-- unique values in each dimension(helps in how data might be grouped by or segmented)

-- explore all the countries that our customers come from

select distinct country from gold.dim_customers;

select country, count(country) from gold.dim_customers
group by country
having country = 'n/a';


-- explore all the products categories 

select distinct category, subcategory, product_name from gold.dim_products

order by 1,2,3;

-- identify the earliest and the latest dates(boundries)(range of the date)

select min(order_date), max(order_date), min(shipping_date), max(shipping_date),

min(due_date), max(due_date) from gold.fact_sales;

-- find the date of the first and last order

select min(order_date), max(order_date) from gold.fact_sales;

-- how many years of sales are avaiable

select  DATEDIFF(year, min(order_date), max(order_date)) from gold.fact_sales;

-- the youngest and the oldest customer in year

select datediff(year, min(birthdate), SYSDATETIME()), datediff(year, max(birthdate), sysdatetime()) from gold.dim_customers;

-- find the total sales

select sum(sales_amount) as total_sales from gold.fact_sales;

-- find how many items are sold

select sum(quantity) as amount_of_sold_items from gold.fact_sales;

-- find the average selling price

select avg(price) as avg_sales_price from gold.fact_sales;

-- find the total number of orders

select count(order_number) as number_of_orders from gold.fact_sales;

select count(distinct(order_number)) as number_of_orders from gold.fact_sales;

-- find the total number of products

select count(product_id) as number_of_products from gold.dim_products;

-- find the total number of customers

select count(customer_id) as number_of_customers from gold.dim_customers;


-- find the total number of customers that has placed an order

select count(distinct(customer_key)) as number_of_customers  from gold.fact_sales


-- presenting all the business needs in one query


select 'total_sales' as measure_name, sum(sales_amount) as measure_value  from gold.fact_sales

union all

select 'amount_of_sold_items' as measure_name, sum(quantity) as measure_value   from gold.fact_sales

union all

select 'avg_sales_price' as  measure_name, avg(price) as measure_value  from gold.fact_sales

union all

select ' number_of_orders' as  measure_name, count(order_number) as measure_value from gold.fact_sales

union all

select 'number_of_products' as  measure_name, count(product_id) as measure_value  from gold.dim_products

union all

select 'number_of_customers' as  measure_name, count(customer_id) as measure_value  from gold.dim_customers

union all

select 'number_of_customers' as  measure_name, count(distinct(customer_key)) as measure_value  from gold.fact_sales;


-- find total customers by countries

select country, count(customer_key) as total_customers  from gold.dim_customers

group by country

order by total_customers desc;


-- find total customers by gender

select gender, count(customer_key) as total_customers  from gold.dim_customers

group by gender

order by total_customers desc;


-- find total products by category

select category, count(product_key) as total_products from gold.dim_products

group by category

order by total_products desc;


-- what is the average costs in each category?

select category, AVG(cost) as average_costs  from gold.dim_products

group by category

order by average_costs desc;


-- what is the total revenue generated for each category?

select  p.category, sum(s.sales_amount) as revenue from gold.fact_sales s

left join  gold.dim_products p on s.product_key = p.product_key

group by p.category

order by revenue desc;

-- find total revenue is generated by each customer

select  c.first_name, c.last_name,  sum(s.sales_amount) as revenue from gold.fact_sales s

left join  gold.dim_customers c on s.customer_key = c.customer_key

group by c.first_name, c.last_name

order by revenue desc;


-- what is the distribution of sold items across countries?

select c.country, sum(s.quantity) as sold_items from gold.dim_customers c

left join gold.fact_sales s on c.customer_key = s.customer_key

group by c.country

order by  sold_items desc;



-- which 5 products generate the highest revenue in two ways


select top 5 p.product_name, sum(s.sales_amount) as highest_revenue, row_number() over(order by sum(s.sales_amount) desc)

from gold.dim_products p

left join gold.fact_sales s  on p.product_key = s.product_key

group by p.product_name;



select top 5

p.product_name, sum(s.sales_amount) as highest_revenue from gold.dim_products p

left join gold.fact_sales s  on p.product_key = s.product_key

group by p.product_name

order by highest_revenue desc;


-- what are the 5 worst_performing products terms of sales in two ways

select top 5 p.product_name, sum(s.sales_amount) as lowest_revenue, row_number() over(order by sum(s.sales_amount))

from gold.dim_products p

left join gold.fact_sales s  on p.product_key = s.product_key

group by p.product_name;



select top 5

p.product_name, sum(s.sales_amount) as lowest_revenue from gold.dim_products p

left join gold.fact_sales s  on p.product_key = s.product_key

group by p.product_name

order by lowest_revenue;

-- find the top 10 customers who have generated the highest revenue and 3 customers with the fewest orders placed


select top 10 c.first_name,c.last_name,  sum(s.sales_amount) as highest_revenue, row_number() over(order by sum(s.sales_amount) desc)

from gold.dim_customers c

left join gold.fact_sales s  on c.customer_key = s.customer_key

group by c.first_name,c.last_name;



select top 3 c.first_name,c.last_name,  count(s.order_number) as total_order, row_number() over(order by  count(s.order_number))

from gold.dim_customers c

left join gold.fact_sales s  on c.customer_key = s.customer_key

group by c.first_name,c.last_name;






select * from gold.dim_customers;

select * from gold.dim_products;

select * from gold.fact_sales;